In [1]:
import numpy as np

In [2]:
!cat test.csv

# test comment
1.0,3.0,5.0
2.0,4.0,6.0


In [3]:
temp = np.loadtxt('test.csv',delimiter=',')
temp

array([[ 1.,  3.,  5.],
       [ 2.,  4.,  6.]])

In [4]:
!ls -a

.                        150417_try_loadtxt.ipynb test3.csv
..                       test.csv
.ipynb_checkpoints       test2.csv


In [10]:
!cat test2.csv

# First line is layer exposure time in seconds. Next lines are measured membrane thicknesses in pixels. 0 means there was no membrane.,,,
2.00E+00,1.50E+00,1.00E+00,5.00E-01
2.87E+02,2.13E+02,1.77E+02,7.70E+01
3.11E+02,2.63E+02,1.61E+02,5.10E+01
3.15E+02,2.20E+02,1.51E+02,6.40E+01
3.11E+02,2.60E+02,1.76E+02,6.20E+01
2.88E+02,2.42E+02,1.60E+02,5.90E+01
3.02E+02,2.40E+02,1.45E+02,5.80E+01

In [12]:
temp2 = np.loadtxt('test2.csv',delimiter=',')
temp2

array([[   2. ,    1.5,    1. ,    0.5],
       [ 287. ,  213. ,  177. ,   77. ],
       [ 311. ,  263. ,  161. ,   51. ],
       [ 315. ,  220. ,  151. ,   64. ],
       [ 311. ,  260. ,  176. ,   62. ],
       [ 288. ,  242. ,  160. ,   59. ],
       [ 302. ,  240. ,  145. ,   58. ]])

In [13]:
!cat test3.csv

# First line is layer exposure time in seconds. Next lines are measured membrane thicknesses in pixels. 0 means there was no membrane.
# 2nd line
# 3rd line
# 4th line
# 5th line
# 6th line
2.00E+00,1.50E+00,1.00E+00,5.00E-01
2.87E+02,2.13E+02,1.77E+02,7.70E+01
3.11E+02,2.63E+02,1.61E+02,5.10E+01
3.15E+02,2.20E+02,1.51E+02,6.40E+01
3.11E+02,2.60E+02,1.76E+02,6.20E+01
2.88E+02,2.42E+02,1.60E+02,5.90E+01
3.02E+02,2.40E+02,1.45E+02,5.81E+01

In [14]:
temp3 = np.loadtxt('test3.csv',delimiter=',')
temp3

array([[   2. ,    1.5,    1. ,    0.5],
       [ 287. ,  213. ,  177. ,   77. ],
       [ 311. ,  263. ,  161. ,   51. ],
       [ 315. ,  220. ,  151. ,   64. ],
       [ 311. ,  260. ,  176. ,   62. ],
       [ 288. ,  242. ,  160. ,   59. ],
       [ 302. ,  240. ,  145. ,   58.1]])