In [1]:
import numpy as np

In [28]:
numpnts = 11
xx = np.linspace(-1,1,numpnts)
yy = np.linspace(-1,1,numpnts)
zz = np.linspace(-1,1,numpnts)
data_inorout = np.zeros(shape=(numpnts,numpnts,numpnts))


print xx.shape, data_inorout.shape


(11,) (11, 11, 11)


In [29]:
print xx

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [30]:
%timeit xx*yy

The slowest run took 24.46 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 536 ns per loop


In [31]:
limit = 0.55
for i in range(numpnts):
    for j in range(numpnts):
        for k in range(numpnts):
            r_squared = xx[i]**2 + yy[j]**2 + zz[k]**2
            if r_squared < limit**2:
                data_inorout[i,j,k] = 1.0
                #print np.sqrt(r_squared),limit,i,j,k,xx[i],yy[j],zz[k]

In [35]:
print data_inorout[3:8,3:8,2:9]

[[[ 0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]]

 [[ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]]

 [[ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  1.  1.  1.  1.  1.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  0.  1.  1.  1.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.]]]


In [36]:
print xx

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
