In [1]:
import numpy as np

In [3]:
buildxy_inches = np.array([7.5,4.3])  # largest xy build size
buildxy_inches

array([ 7.5,  4.3])

In [4]:
buildxy_mm = buildxy_inches * 25.4
buildxy_mm

array([ 190.5 ,  109.22])

In [5]:
buildxy_pixels = buildxy_mm / 0.1  # 100 um xy-resolution
buildxy_pixels

array([ 1905. ,  1092.2])

1080p HD pixel count is 1920x1080 pixels, so the Titan 1 specs are consistent with using a 1080p projector